remote_theme: teznote/tezskin@v6.0.0

title: "Tez'Note"
main-top-msg: "이것저것 기록하는 노트같은 블로그"
footer-msg: "Powered by 깃허브 페이지"
url: "https://teznote.github.io"
permalink: /post/:title
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
future: true

cats:
- id: excel_formula
  title: Useful Excel Formulas
  order: asc