remote_theme: teznote/tezskin@v2.1.0

title: "Tez'Note"
desc: "이것저것 끄적이고 나중에 다시 꺼내보는<br class='mobile'/> 노트와 같은 공간"
url: "https://teznote.github.io"

permalink: /post/:title

cats:
- id: web
  title: Web & Blog Develop
- id: algorithm
  title: Algorithm & Data Structure

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
