remote_theme: teznote/tezskin@v3.0.6

title: "Tez'Note"
desc: "이것저것 끄적이는 노트같은 공간"
url: "https://teznote.github.io"

permalink: /post/:title

navtags:
- id: leetcode
  title: Leetcode Problems
  subs:
  - id: seq
    title: Array or String
  - id: graph
    title: Graph
  - id: design
    title: Algorithm Design
- id: msoffice
  title: MS Office Tips
  subs:
  - id: formula
    title: Useful Excel Formula
- id: dev
  title: Development
  subs:
  - id: web
    title: Web and Blog
    order: desc
  - id: python
    title: Python Tips
    order: desc

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
