remote_theme: teznote/tezskin@v5.0.1

title: "Tez'Note"
desc: "이것저것 끄적이는 노트같은 공간"
url: "https://teznote.github.io"

permalink: /post/:title

cats:
- id: leetcode_easy
  title: Leetcode Easy
- id: leetcode_medium
  title: Leetcode Medium
- id: excel_formula
  title: Excel Formula
  order: asc

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
