remote_theme: teznote/tezdocs
title: Tez'Note
permalink: /post/:title
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
future: true

cats:
  - id: msoffice
    title: MS Office
    subs:
      - id: formula
        title: Excel Formula
        order: title
