remote_theme: teznote/tezdocs@v2.0.0

title: "Tez'Note"
footer-msg: "Themed by Tez &&<br/>Powered by Github Pages"
url: "https://teznote.github.io"
permalink: /post/:title
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
future: true

c-color: #f5ab35

cats:
- id: msoffice
  title: MS Office
  subs:
  - id: excel_formula
    title: Useful Excel Formulas
    order: title
  - id: template
    title: Templates
    order: title