remote_theme: teznote/tezdocs@v1.0.1

title: "Tez'Note"
main-top-msg: "이것저것 기록하는 노트같은 블로그"
footer-msg: "Powered by 깃허브 페이지"
url: "https://teznote.github.io"
permalink: /post/:title
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
future: true
navtags:
- id: msoffice
  title: MS Office Tips
  subs:
  - id: formula
    title: Useful Excel Formula
- id: dev
  title: Develop Blog
  subs:
    - id: python
      title: Python Tips
    - id: web
      title: Web Develop
