remote_theme: teznote/tezskin@v3.0.6

title: "Tez'Note"
desc: "이것저것 끄적이는 노트같은 공간"
url: "https://teznote.github.io"

permalink: /post/:title

navtags:
- id: leetcode
  title: Leetcode Problems
  subs:
  - id: array
    title: Array
- id: msoffice
  title: MS Office Tips
  subs:
  - id: formula
    title: Useful Excel Formula

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
