remote_theme: teznote/tezskin@v3.0.4

title: "Tez'Note"
desc: "이것저것 끄적이는 "
url: "https://teznote.github.io"

permalink: /post/:title

navtags:
- id: coding
  title: Programming & Coding
  subs:
  - id: algorithm
    title: Algorithm
  - id: python
    title: Python Code Snippet
  - id: dev
    title: Development Note
    order: desc

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
