name: Tez'Note Deployment
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: node build md
      - name: Check if there are any changes
        id: verify_diff
        run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: update
        if: steps.verify_diff.outputs.changed == 'true'
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git add .
          git commit -m "deployment"
          git push
      - name: Upload artifact
        if: steps.verify_diff.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        if: steps.verify_diff.outputs.changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v2