name: Tez'Note Deployment
on:
  push:
    branches: [ main, gh-pages ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout pages in main
        uses: actions/checkout@v4
        with:
          ref: main
          path: './_pages'
      - run: ls -al
      - name: checkout build library in gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: '.'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm i
      - run: node build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_site'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2